### ISSUE TITLE
В сообщение к Exception на отрицательную ставку кредитования написано "Накопительная ставка"

### ISSUE THREAD

**Issue by esaukova** [esaukova/team-project-bank#1]
# Описание
Объект public CreditAccount имеет исключения вида IllegalArgumentException с некорректным сообщением  "**Накопительная ставка** не может быть отрицательной, а у вас: " 

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/e70ebe1686fe661b7eb744c8496ead35fa2ccc4e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19-L22

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L22) в IDEA
2. Обратить внимание сообщение для IllegalArgumentException в объекте https://github.com/esaukova/team-project-bank/blob/e70ebe1686fe661b7eb744c8496ead35fa2ccc4e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

*Ожидаемый результат:* исключения вида IllegalArgumentException имеет сообщение  "Ставка кредитования не может быть отрицательной, а у вас: " 

*Фактический результат:* исключения вида IllegalArgumentException имеет сообщение  "Накопительная ставка не может быть отрицательной, а у вас: " 

# Скриншот
![Bag1](https://github.com/esaukova/team-project-bank/assets/81514189/cf0e9ed5-6595-489e-abd9-42f09472bee4)

# Окружение 
* **Операционная система:** Windows 10 Home Single Language
*  **IDE:** IntelliJ IDEA 2023.1.2 (Ultimate Edition)
*  **Java:** OpenJDK 11

**Comment by Le-ha12** [comment]
![Скриншот 15-08-2023 203700](https://github.com/esaukova/team-project-bank/assets/134203394/bcc19ad6-31f7-4020-ad77-3c42a3c641f8)
@esaukova
