### ISSUE TITLE
Не отображается исключение IllegalArgumentException, если изначально баланс больше максимального

### ISSUE THREAD

**Issue by Le-ha12** [esaukova/team-project-bank#10]
# Описание
В первичных требованиях указано, что если параметры некорректны : начальный баланс не может быть больше максимального то должно отобразиться исключения, вида IllegalArgumentException. Тест не проходит, т.к. условия не реализовывают требования

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/a50b42f60a8b8fe44aeb01ce51944700b26c0081/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект класса SavingAccount с начальным балансом 3_000, минимальным балансом 1_000, максимальный баланс 2_000 и ставкой 5.
3. Запустить тест ThrowExceptionForBalanceMore
4. Произвести проверку на вывод исключения вида IllegalArgumentException при создании объекта, если начальный баланс больше максимального

Ожидаемый результат: выкидывается исключение и тест проходит
Фактический результат: исключение не выкидывается, а выдает значение 3 000

# Скриншот
![Скриншот-12-08-2023 10_27_12](https://github.com/esaukova/team-project-bank/assets/134203394/7e3d7c19-0654-4707-8062-48e9fcd062a7)

# Окружение
Операционная система: Windows 10 Pro
IDE:IntelliJ IDEA 2023.1.3 (Community Edition)
Java: OpenJDK 11

**Comment by esaukova** [comment]
![Bug10_solved](https://github.com/esaukova/team-project-bank/assets/81514189/6bd6ba70-0c0a-49d6-ae7e-efd304ed376a)
![Exccption_InitBalance](https://github.com/esaukova/team-project-bank/assets/81514189/4b3f7a9b-7e53-4df0-b939-1a2845339cac)
Solved @Le-ha12
