### ISSUE TITLE
Не отображается исключение IllegalArgumentException, если изначально баланс меньше минимального

### ISSUE THREAD

**Issue by Le-ha12** [esaukova/team-project-bank#11]
# Описание
В методе ThrowExceptionForBalanceLess класса SavingAccountTest ожидается, что будет вызвано исключение IllegalArgumentException, однако исключение не было сгенерировано.

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/a50b42f60a8b8fe44aeb01ce51944700b26c0081/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект класса SavingAccount с начальным балансом 0, минимальным балансом 1_000, максимальный баланс 2_000 и ставкой 5.
3. Запустить тест ThrowExceptionForBalanceLess
4. Произвести проверку на вывод исключения вида IllegalArgumentException при создании объекта, если начальный баланс меньше минимального 

Ожидаемый результат: выкидывается исключение и тест проходит
Фактический результат: исключение не выкидывается, а выдает значение 0

# Скриншот
![Скриншот-12-08-2023 10_54_38](https://github.com/esaukova/team-project-bank/assets/134203394/18cc227f-c8ba-4569-ac1d-5c88e3a24473)

# Окружение
Операционная система: Windows 10 Pro
IDE:IntelliJ IDEA 2023.1.3 (Community Edition)
Java: OpenJDK 11

**Comment by esaukova** [comment]
![Bug11_solved](https://github.com/esaukova/team-project-bank/assets/81514189/0ea907b4-0a98-46e3-af93-92d03acc17a9)

Solved @Le-ha12 
Используется исключение с InitBalance
