### ISSUE TITLE
Неверный подсчет и отображение баланса при использование класса pay 

### ISSUE THREAD

**Issue by Le-ha12** [esaukova/team-project-bank#12]
# Описание
По условию требований, в результате успешного вызова этого метода, баланс должен уменьшиться на сумму покупки. Если же операция может привести к некорректному состоянию счёта (например, баланс может уйти в минус), то операция должна завершиться вернув false и ничего не поменяв на счёте. 

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/a50b42f60a8b8fe44aeb01ce51944700b26c0081/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект класса SavingAccount с начальным балансом 1_000, минимальным балансом 1_000, максимальный баланс 15_000 и ставкой 5.
3. Запустить метод pay со значением 500.
4. Запустить тест shouldAddBelowMinBalance и посмотреть вывод консоли.

Ожидаемый результат: консоль возвращает false
Фактический результат: консоль не выдает правильное значение 

# Скриншот
![Скриншот-12-08-2023 11_18_04](https://github.com/esaukova/team-project-bank/assets/134203394/27c660d7-5a39-42e1-87d6-ce28cb2889da)

# Окружение
Операционная система: Windows 10 Pro
IDE:IntelliJ IDEA 2023.1.3 (Community Edition)
Java: OpenJDK 11

**Comment by esaukova** [comment]
![Bug12_solved](https://github.com/esaukova/team-project-bank/assets/81514189/b07cd601-3a25-40ad-875e-52fc88fe5b27)
![Method_pay](https://github.com/esaukova/team-project-bank/assets/81514189/3d50432d-8899-4ccb-831d-91fa21be4032)
Solved @Le-ha12
