### ISSUE TITLE
Не выходит исключение IllegalArgumentException при отрицательном начальном балансе

### ISSUE THREAD

**Issue by Le-ha12** [esaukova/team-project-bank#13]
# Описание
В первичных требованиях указано, что если параметры некорректны : начальный баланс не может быть больше отрицательным то должно отобразиться исключения, вида IllegalArgumentException. Тест не проходит, т.к. условия не реализовывают требования

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/a50b42f60a8b8fe44aeb01ce51944700b26c0081/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект класса SavingAccount с начальным балансом -1_000, минимальным балансом 1_000, максимальный баланс 15_000 и ставкой 5.
3. Запустить тест ThrowExceptionForInitialBalanceи.
4. Произвести проверку на вывод исключения вида IllegalArgumentException при создании объекта, если начальный баланс отрицательный

Ожидаемый результат: выкидывается исключение и тест проходит
Фактический результат: исключение не выкидывается, а выдает значение -1000

# Скриншот
![Скриншот-12-08-2023 11_25_28](https://github.com/esaukova/team-project-bank/assets/134203394/2fbbef60-a189-4f06-9c4b-a03ded7a45d1)

# Окружение
Операционная система: Windows 10 Pro
IDE:IntelliJ IDEA 2023.1.3 (Community Edition)
Java: OpenJDK 11

**Comment by esaukova** [comment]
![Bug13_solved](https://github.com/esaukova/team-project-bank/assets/81514189/3991bc2f-2995-462c-bd53-2cd3b41ef29c)

Solved @Le-ha12 
Используется исключение для InitBalance
