### ISSUE TITLE
Не выходит исключение IllegalArgumentException при отрицательном минимальном балансе

### ISSUE THREAD

**Issue by Le-ha12** [esaukova/team-project-bank#14]
# Описание
В первичных требованиях указано, что если параметры некорректны : минимальный баланс не может быть больше отрицательным то должно отобразиться исключения, вида IllegalArgumentException. Тест не проходит, т.к. условия не реализовывают требования

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/a50b42f60a8b8fe44aeb01ce51944700b26c0081/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект класса SavingAccount с начальным балансом 1_000, минимальным балансом -100, максимальный баланс 15_000 и ставкой 5.
3. Запустить тест ThrowExceptionForMinBalance.
4. Произвести проверку на вывод исключения вида IllegalArgumentException при создании объекта, если минимальный баланс отрицательный.

Ожидаемый результат: выкидывается исключение и тест проходит
Фактический результат: исключение не выкидывается, а выдает значение 1000

# Скриншот
![Скриншот-12-08-2023 11_31_13](https://github.com/esaukova/team-project-bank/assets/134203394/5e55738d-2eb8-4ef2-a6aa-ed2c0ebefb1c)

# Окружение
Операционная система: Windows 10 Pro
IDE:IntelliJ IDEA 2023.1.3 (Community Edition)
Java: OpenJDK 11

**Comment by esaukova** [comment]
![Bug14_solved](https://github.com/esaukova/team-project-bank/assets/81514189/ac9aba64-919a-4d26-88e1-f8180e21cde0)
![Exception_MinBalance](https://github.com/esaukova/team-project-bank/assets/81514189/cda99774-1a73-4501-8a65-7ec42d913536)

Solved @Le-ha12 
Используется исключение для MinBalance
