### ISSUE TITLE
Не выходит исключение IllegalArgumentException при максимальный баланс равен минимальному.

### ISSUE THREAD

**Issue by Le-ha12** [esaukova/team-project-bank#15]
# Описание
В первичных требованиях указано, что если параметры некорректны : максимальный баланс не может быть отрицательным то должно отобразиться исключения, вида IllegalArgumentException. Тест не проходит, т.к. условия не реализовывают требования

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/a50b42f60a8b8fe44aeb01ce51944700b26c0081/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект класса SavingAccount с начальным балансом 1_000, минимальным балансом 1_000, максимальный баланс 1_000 и ставкой 5.
3. Запустить тест ThrowExceptionForMaxBalance.
4. Произвести проверку на вывод исключения вида IllegalArgumentException при создании объекта, если минимальный баланс равен максимальному.

Ожидаемый результат: выкидывается исключение и тест проходит
Фактический результат: исключение не выкидывается, а выдает значение 1000

# Скриншот
![Скриншот-12-08-2023 11_39_08](https://github.com/esaukova/team-project-bank/assets/134203394/f65f2170-2ae3-4751-b410-b6ddbe7c6224)

# Окружение
Операционная система: Windows 10 Pro
IDE:IntelliJ IDEA 2023.1.3 (Community Edition)
Java: OpenJDK 11

**Comment by esaukova** [comment]
![Bug15_solved](https://github.com/esaukova/team-project-bank/assets/81514189/b27de22c-4b5f-428e-9c41-6ea58ebc2ddd)

Solved @Le-ha12  
Используется исключение для MinBalance
