### ISSUE TITLE
При расчет процентов за год, выводит неверные значения.

### ISSUE THREAD

**Issue by Le-ha12** [esaukova/team-project-bank#16]
# Описание
Неправильный расчет процентов за год.

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/a50b42f60a8b8fe44aeb01ce51944700b26c0081/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L87

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект класса SavingAccount с начальным балансом 8_000, минимальным балансом 1_000, максимальный баланс 10_000 и ставкой 5.
3. Запустить метод add со значением 1_000.
4. Запустить тест shouldInterestCalculationWithAdd и посмотреть вывод консоли.

Ожидаемый результат: ответ должен быть 450
Фактический результат: ответ 50

# Скриншот
![Скриншот-12-08-2023 11_49_42](https://github.com/esaukova/team-project-bank/assets/134203394/ff2a00db-5a8f-4927-abfb-695c02533177)

# Окружение

Операционная система: Windows 10 Pro
IDE:IntelliJ IDEA 2023.1.3 (Community Edition)
Java: OpenJDK 11

**Comment by esaukova** [comment]
![Bug16_solved](https://github.com/esaukova/team-project-bank/assets/81514189/73ee9edd-786f-4389-abbe-1dc90cff3242)

Дефект был из-за некорректной работы  метода add, который был исправлен ранее  @Le-ha12
