### ISSUE TITLE
Исключение IllegalArgumentException не работает при отрицательном значении кредитного лимита

### ISSUE THREAD

**Issue by esaukova** [esaukova/team-project-bank#2]
# Описание
Объект CreditAccount при создании с отрицательным значением кредитного лимита не выбрасывает исключение с сообщением "Кредитный лимит не может быть отрицательным, а у вас: " 

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/e70ebe1686fe661b7eb744c8496ead35fa2ccc4e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/main/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать тест для объект класса CreditAccount со следующими параметрами:
                  - initialBalance = 1_000;
                  - creditLimit = - 5_000;
                  - rate = 15;                      
    
      _public void shouldThrowExceptionWhenCreditLimitNegative() {
        Assertions.assertThrows(IllegalArgumentException.class,
                () -> {new CreditAccount(1_000, -5_000, 15);
                });_
    

3. Запустить тест
4. Проверить результат в консоли 
        
*Ожидаемый результат:* тест пройден. Выкидывается исключение вида IllegalArgumentException 

*Фактический результат:* тест не пройден. Не было выкинуто исключение вида IllegalArgumentException
# Тест
https://github.com/esaukova/team-project-bank/blob/2bab08c0a4800b44611f8a55ac39e2d50f302ad7/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L16

# Скриншот
![Bug2](https://github.com/esaukova/team-project-bank/assets/81514189/9b53d64f-964b-4f8f-86a8-3647e26c34bc)

# Окружение 
* **Операционная система:** Windows 10 Home Single Language
*  **IDE:** IntelliJ IDEA 2023.1.2 (Ultimate Edition)
*  **Java:** OpenJDK 11

**Comment by Le-ha12** [comment]
![Скриншот 15-08-2023 190433](https://github.com/esaukova/team-project-bank/assets/134203394/fda7af34-4d5e-4b65-8236-3cd91dd54d14)
![Скриншот 15-08-2023 190507](https://github.com/esaukova/team-project-bank/assets/134203394/621bdd6d-7513-48e5-ba99-14329d11ba09)
@esaukova
