### ISSUE TITLE
Исключение IllegalArgumentException не работает при отрицательном значении начального баланса

### ISSUE THREAD

**Issue by esaukova** [esaukova/team-project-bank#3]
# Описание
Объект CreditAccount при создании с отрицательным значением начального баланса не выбрасывает исключение с сообщением "Начальный баланс не может быть отрицательным, а у вас: " 

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/e70ebe1686fe661b7eb744c8496ead35fa2ccc4e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/main/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать тест для объект класса CreditAccount со следующими параметрами:
                  - initialBalance = - 1_000;
                  - creditLimit = 5_000;
                  - rate = 15;                      
    
      _public void shouldThrowExceptionWhenInitialBalanceNegative() {
        Assertions.assertThrows(IllegalArgumentException.class,
                () -> {new CreditAccount(-1_000, 5_000, 15);
                });_
    

3. Запустить тест
4. Проверить результат в консоли 
        
*Ожидаемый результат:* тест пройден. Выкидывается исключение вида IllegalArgumentException 

*Фактический результат:* тест не пройден. Не было выкинуто исключение вида IllegalArgumentException
# Тест
https://github.com/esaukova/team-project-bank/blob/2bab08c0a4800b44611f8a55ac39e2d50f302ad7/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L9

# Скриншот
![Bug3](https://github.com/esaukova/team-project-bank/assets/81514189/7d1699e2-0c3f-476f-87d6-ac854bbe71ea)

# Окружение 
* **Операционная система:** Windows 10 Home Single Language
*  **IDE:** IntelliJ IDEA 2023.1.2 (Ultimate Edition)
*  **Java:** OpenJDK 11

**Comment by Le-ha12** [comment]
![Скриншот 15-08-2023 191423](https://github.com/esaukova/team-project-bank/assets/134203394/6cbd8c9b-19a0-4674-a5f3-d5b2f92eaebd)
![Скриншот 15-08-2023 191436](https://github.com/esaukova/team-project-bank/assets/134203394/051f73c7-a51c-4dd4-8e15-823a89e061a6)
@esaukova
