### ISSUE TITLE
Неправильно считается баланс после совершения покупок на сумму не превышающую InitBalance+CreditLimit

### ISSUE THREAD

**Issue by esaukova** [esaukova/team-project-bank#4]
# Описание
При совершении покупок на сумму, которая не превышает сумму баланса и кредитного лимита, остаточный баланс рассчитывается некорректно 

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/e70ebe1686fe661b7eb744c8496ead35fa2ccc4e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/main/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса CreditAccount со следующими параметрами:
                  - initialBalance = 500;
                  - creditLimit = 5_000;
                  - rate = 15;  
3. Добавить метод **pay** с параметром 499               
4. Запустить тест
5. Проверить результат в консоли 
        
*Ожидаемый результат:* тест пройден. Баланс: 1

*Фактический результат:* тест не пройден. Баланс: -499

# Тест
https://github.com/esaukova/team-project-bank/blob/2bab08c0a4800b44611f8a55ac39e2d50f302ad7/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L44

# Скриншот
![Bug4](https://github.com/esaukova/team-project-bank/assets/81514189/d1a0b742-e627-412f-a1a3-22f7c0269772)

# Окружение 
* **Операционная система:** Windows 10 Home Single Language
*  **IDE:** IntelliJ IDEA 2023.1.2 (Ultimate Edition)
*  **Java:** OpenJDK 11

**Comment by Le-ha12** [comment]
![Скриншот 15-08-2023 195614](https://github.com/esaukova/team-project-bank/assets/134203394/1f30d26b-1f8e-4a3e-bcad-f37ffb00f498)
![Скриншот 15-08-2023 195600](https://github.com/esaukova/team-project-bank/assets/134203394/9049dc0a-2548-431d-9113-8af98ac8d7f9)
@esaukova
