### ISSUE TITLE
При оплате на сумму, превышающую InitBalance+CreditLimit, операция выполняется

### ISSUE THREAD

**Issue by esaukova** [esaukova/team-project-bank#5]
# Описание
При совершении покупок на сумму, которая превышает сумму баланса и кредитного лимита, выдается пересчитанный баланс, а не изначальный баланс

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/e70ebe1686fe661b7eb744c8496ead35fa2ccc4e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/main/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса CreditAccount со следующими параметрами:
                  - initialBalance = 0;
                  - creditLimit = 5_000;
                  - rate = 15;  
3. Добавить метод **pay** с параметром 5_001               
4. Запустить тест
5. Проверить результат в консоли 
        
*Ожидаемый результат:* тест пройден. Баланс: 0

*Фактический результат:* тест не пройден. Баланс: -5001

# Тест
https://github.com/esaukova/team-project-bank/blob/ce5a151ec724cba40c7f597143d7fbd89be0232c/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L52

# Скриншот
![Bug5](https://github.com/esaukova/team-project-bank/assets/81514189/dfdead6c-046c-4542-83a4-eb044889bca6)

# Окружение 
* **Операционная система:** Windows 10 Home Single Language
*  **IDE:** IntelliJ IDEA 2023.1.2 (Ultimate Edition)
*  **Java:** OpenJDK 11

**Comment by Le-ha12** [comment]
![Скриншот 15-08-2023 200428](https://github.com/esaukova/team-project-bank/assets/134203394/5fd4b77c-09ad-48ad-b7e3-70f68c43ed63)
![Скриншот 15-08-2023 195614](https://github.com/esaukova/team-project-bank/assets/134203394/b569525c-1377-4c7f-8da2-6cf1dc609961)
@esaukova
