### ISSUE TITLE
При пополнение CreditAccount с положительным InitBalance не происходит увеличение баланса на сумму пополнения

### ISSUE THREAD

**Issue by esaukova** [esaukova/team-project-bank#6]
# Описание
Неверное увеличение баланса при пополнение CreditAccount, у которого положительный начальный баланс.
# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/e70ebe1686fe661b7eb744c8496ead35fa2ccc4e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/main/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса CreditAccount со следующими параметрами:
                  - initialBalance = 1_000;
                  - creditLimit = 5_000;
                  - rate = 15;  
3. Добавить метод **add** с параметром 3_000               
4. Запустить тест
5. Проверить результат в консоли 
        
*Ожидаемый результат:* тест пройден. Баланс: 4000

*Фактический результат:* тест не пройден. Баланс: 3000

# Тест
https://github.com/esaukova/team-project-bank/blob/ce5a151ec724cba40c7f597143d7fbd89be0232c/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L83

# Скриншот
![Bug6](https://github.com/esaukova/team-project-bank/assets/81514189/55a27f12-f2d3-49e2-91b4-42f602ab11cb)

# Окружение 
* **Операционная система:** Windows 10 Home Single Language
*  **IDE:** IntelliJ IDEA 2023.1.2 (Ultimate Edition)
*  **Java:** OpenJDK 11

**Comment by Le-ha12** [comment]
![Скриншот 15-08-2023 200728](https://github.com/esaukova/team-project-bank/assets/134203394/15f1d270-bfc7-4670-b2e8-c84b09b8e170)
![Скриншот 15-08-2023 200717](https://github.com/esaukova/team-project-bank/assets/134203394/a4860f79-ee2b-4a2e-9bdb-99bfc6d13fcc)
@esaukova
