### ISSUE TITLE
Происходит расчёт процентов при положительном балансе счёта CreditAccount

### ISSUE THREAD

**Issue by esaukova** [esaukova/team-project-bank#7]
# Описание
Происходит расчёт годовых процентов на CreditAccount при положительном балансе счёта 
# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/e70ebe1686fe661b7eb744c8496ead35fa2ccc4e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/main/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса CreditAccount со следующими параметрами:
                  - initialBalance = 200;
                  - creditLimit = 5_000;
                  - rate = 15;             
4. Запустить тест с account.yearChange()
5. Проверить результат в консоли 
        
*Ожидаемый результат:* тест пройден. YearChange: 0

*Фактический результат:* тест не пройден. YearChange: 30

# Тест
https://github.com/esaukova/team-project-bank/blob/ce5a151ec724cba40c7f597143d7fbd89be0232c/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L113

# Скриншот
![Bug7](https://github.com/esaukova/team-project-bank/assets/81514189/8c10c82e-87dc-4a90-b7a1-7eac56c36989)

# Окружение 
* **Операционная система:** Windows 10 Home Single Language
*  **IDE:** IntelliJ IDEA 2023.1.2 (Ultimate Edition)
*  **Java:** OpenJDK 11

**Comment by Le-ha12** [comment]
![Скриншот 15-08-2023 201128](https://github.com/esaukova/team-project-bank/assets/134203394/7cb95137-3732-440e-a65d-27752fdd56fb)
![Скриншот 15-08-2023 201139](https://github.com/esaukova/team-project-bank/assets/134203394/0537b168-2f41-4a95-9334-4b1ad91f5000)
@esaukova
