### ISSUE TITLE
Неверный расчет баланса карты, в методе add после ее пополнения

### ISSUE THREAD

**Issue by Le-ha12** [esaukova/team-project-bank#9]
# Описание
В методе add при пополнении карты, итоговый баланс рассчитывается не верно, показывая только сумму, равную пополнению, но без учета начального баланса.

# Локация дефекта
https://github.com/esaukova/team-project-bank/blob/a50b42f60a8b8fe44aeb01ce51944700b26c0081/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/esaukova/team-project-bank/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект класса SavingAccount с начальным балансом 2_000, минимальным балансом 1_000, максимальный баланс 10_000 и ставкой 5.
3. Запустить метод add со значением 3_000.
4. Запустить тест public void shouldAddLessThanMaxBalance и посмотреть вывод консоли.

Ожидаемый результат: сумма баланса должна увеличится на сумму пополнение и в итоге равняться 5 000
Фактический результат: после пополнения в итоге баланс равен только сумме пополнения, а именно 3 000

# Скриншот
![Скриншот-12-08-2023 09_55_41](https://github.com/esaukova/team-project-bank/assets/134203394/de415f30-df3f-41da-98c8-6d6eace7dd7e)

# Окружение
Операционная система: Windows 10 Pro
IDE:IntelliJ IDEA 2023.1.3 (Community Edition)
Java: OpenJDK 11

**Comment by esaukova** [comment]
![Bug9_solved](https://github.com/esaukova/team-project-bank/assets/81514189/0d3284d5-fbb0-45ce-bb6e-d47d26cd1249)
![Method_add](https://github.com/esaukova/team-project-bank/assets/81514189/c513585b-2aea-4e88-a941-42879e4f062a)

**Comment by esaukova** [comment]
Solved @Le-ha12
